# UKSFTA Diamond Grade Linting Configuration
# Standards for the unit mod suite

[cfg]
cfg_patches = true
cfg_vehicles = true
missing_semicolon = true

[sqf]
undefined_variable = true
unused_variable = true
private_variable_isolation = true
bis_headers = true
count_comparison = true
# DISABLED: Obstructs advanced heuristic interrogation
if_replacement = false
performance = false

[stringtable]
missing_keys = true
duplicate_keys = true
