[config.file_type]
options.allow_no_extension = true

[stringtables.usage]
options.ignore = []
options.ignore_unused = true

[sqf.banned_commands]
options.ignore = [
    "addPublicVariableEventHandler",
    "createSoundSource"
]

[sqf.var_all_caps]
options.ignore = ["SLX_*"]

[sqf.undefined]
enabled = true
options.check_orphan_code = true

[sqf.unused]
enabled = false

[sqf.shadowed]
enabled = false

[sqf.not_private]
enabled = true

# Disable performance lints that obstruct heuristic engines
[sqf.performance]
enabled = false

[sqf.if_replacement]
enabled = false

ignored = [
    "addons/scripts*.sqf",
]
