name = "UKSF Task Force Alpha - Maps Modpack"
author = "UKSF Taskforce Alpha Team"
prefix = "uksfta"
mapsprefix = "z"


[version]
path = "addons/maps/script_version.hpp"

[files]
include = [
    "addons/*.pbo",
    "addons/*.bisign",
    "keys/*.bikey",
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "README.md"
]

[archive]
directory = "releases"

workshop_id = "3662499431"
workshop_tags = ["Mod", "Map", "Addon"]

[hemtt.signing]
authority = "UKSFTA"
